### ISSUE TITLE
/token/get/list APIのパラメータについて

### ISSUE THREAD

**Issue by Tommy-ND** [authlete/authlete-java-common#33]
/token/get/list API使用時、subjectの値だけでアクセストークンを取得することはできないでしょうか。
現在はclientIdとsubjectが必要なようですが、
clientIdがnullでも可能、もしくは、パラメータにsubjectのみを渡すことが可能なAPIを検討頂けると有り難いです。

**Comment by hidebike712** [comment]
(Authelte 内部の者です。) `/token/get/list` API は「subject の値だけでアクセストークンを取得すること」を許容しています。ただし、authlete-java-common 側では subject の値のみを指定するメソッドは存在しておりません。これについては将来的に追加を検討致します。

**Comment by hidebike712** [comment]
内部検討の結果、諸般の事情により上記メソッドの追加は行わない方針となりました。
subject の値のみを利用して `/token/get/list` API を利用する場合は、`clientIdentifier` パラメーターに `null` を指定して以下の既存メソッドを呼び出して頂くようお願い致します。

* `getTokenList(String clientIdentifier, String subject)`
* `getTokenList(String clientIdentifier, String subject, int start, int end)`

**Comment by Tommy-ND** [comment]
ご対応頂きありがとうございました。大変助かります。
